# Generated by Django 5.0.6 on 2024-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='Registration',
        ),
    ]
